### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by Sequential-circuits** [haotian-liu/LLaVA#14]
can't use it as it always says NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

**Comment by haotian-liu** [comment]
This seems to be an error in the backend.
1. can you see the model list on the top left?
2. There may be an error in the model worker, can you paste the error message here?

**Comment by DifferentComputers** [comment]
I get the same error but I suspect it's because I may be running it on entirely inadequate hardware. Alternately, I may not have the model data installed correctly.

I don't see any model worker error. that would be appearing on the command line process, correct?

**Comment by haotian-liu** [comment]
Hi @DifferentComputers, sorry that I just saw this comment.  It is not a normal behavior of an empty model list.  You need to start the gradio demo after the worker is fully loaded, so as to get the model list.  Please let me know if you have further concerns.

**Comment by corleytd** [comment]
I met the same problem "NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.", but my model list is not empty, there is a model I have applied the delta before, but still the error, some details are as follow:
![image](https://user-images.githubusercontent.com/53808058/235863716-a311bf84-8acc-4312-9e46-1d7e9e09d396.png)

![image](https://user-images.githubusercontent.com/53808058/235863549-929c388b-ce25-46b1-97f2-28f394a49e58.png)

thank you!

**Comment by haotian-liu** [comment]
@corleytd Hi please see my response in #89, thanks.
