### ISSUE TITLE
[Usage] ValueError: The number of image start tokens and image end tokens should be the same.

### ISSUE THREAD

**Issue by Kindpire** [haotian-liu/LLaVA#201]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
ValueError: The number of image start tokens and image end tokens should be the same.
Command:
```
CUDA_VISIBLE_DEVICES='2,3,4,5,6,7' torchrun --nnodes=1 --nproc_per_node=6 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path /usr/dataset/model/vicuna-7b \
    --data_path /usr/dataset/llava_instruct_150k_fix_prefix.json \
    --image_folder /usr/dataset/COCO2014/train2014/train2014 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-7b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 256 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb
```
Hi, I was trying to fine-tune LLaVA on 6x3090, when I set model_max_length>=512, I'll get the error like:
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.
But when I get the model_max_length <= 256. I got the error like:
ValueError: The number of image start tokens and image end tokens should be the same.

Any insights?

**Comment by haotian-liu** [comment]
Hi @Kindpire,

Thank you for your interest in our work.  I am working on the LoRA integration recently and I am testing the performance currently.  I should be able to release a version soon.

Regarding the errors.  The first is due to that flash attention is not supported on RTX 3090 yet, and you can change `train_mem.py` to `train.py` to avoid that issue.
`model_max_length` should be at least 300 in order to fit all image tokens in (there are 256 of them), or the image will be cut off and that's the reason why you see the second error.

Please let me know if you have other questions, thanks.

**Comment by Kindpire** [comment]
Thanks, it works. The only remaining issue is GPU memory now.
