### ISSUE TITLE
[Question] Support for OpenLLaMA

### ISSUE THREAD

**Issue by alfredplpl** [haotian-liu/LLaVA#244]
### Question

OpenLLaMA has been released few days ago.
https://huggingface.co/openlm-research/open_llama_13b

Do you plan to deal with OpenLLaMA?
Is the OpenLLaMA + LLaVA license Apache-2.0?

**Comment by alfredplpl** [comment]
I tested the OpenLLaMA + LLaVA-delta.
But, it does not work correctly. (The image is generated by my model.)

![Screenshot from 2023-06-18 22-43-27](https://github.com/haotian-liu/LLaVA/assets/3625196/44892d48-0b1a-4141-84a5-45d978ac5fa6)

Should we need to train it LLaVA-delta to fix it?

**Comment by nikolaspapastavrou** [comment]
I had the same question. I believe the answers are the following:

"Do you plan to deal with OpenLLaMA?"
I do not know but that would be great

"Is the OpenLLaMA + LLaVA license Apache-2.0?"
No, if the training procedure is the same as mentioned in the paper. Currently, "Training Stage 2: Fine-tuning End-to-End" relies on annotated data that rely on ChatGPT / GPT-4 for their annotations. ChatGPT / GPT-4 cannot be used to make other models for non-commercial purposes.

"But, it does not work correctly. (The image is generated by my model.)"
It makes sense that it does not work because the delta weights were computed using LLaMA as the frozen LLM during training instead of OpenLLaMA.

Should we need to train new LLaVA-delta to fix it?
Yes, exactly, we would need to freeze OpenLLaMA and retrain it to make it compatible with OpenLLaMA. Also, if you are planning on using this for commercial purposes, you would need to avoid using Chat-GPT / GPT-4 for the data annotation.

**Comment by haotian-liu** [comment]
@nikolaspapastavrou 

Thanks for helping answering these!

LLaMA-2 is now supported so commercial usage of the base LLM should be fine now. We'll release a OpenLLaMA-3B checkpoint for lightweight use cases soon.

Thanks.

**Comment by alfredplpl** [comment]
@haotian-liu Thank you for your reply. LLaVA 1.5 based on Llama 2 is very good. I will close this discussion now.
