### ISSUE TITLE
[Question] Why change the implementation of blocking gradients of input embeddings?

### ISSUE THREAD

**Issue by tingxueronghua** [haotian-liu/LLaVA#307]
### Question

Thanks for your awesome work! I noticed that you commit this https://github.com/haotian-liu/LLaVA/commit/871bbd4a5248510156629e00ee5042b74f74764c to solve the issue of abnormal response. However, I have no idea the old implementation will introduce bugs. Is it related with the parallel framework?

**Comment by haotian-liu** [comment]
Hi @tingxueronghua 

Thank you for your interest in this. I remembered that it is mainly because the previous solution will still modify the embeddings for the last iteration, and it seems that it is getting unreasonably large gradients to the token embeddings, which is large enough to make the generation process a mess. By making the change, the generation process is now working properly. Thanks.
