### ISSUE TITLE
The same input prompt, different runs get different results?

### ISSUE THREAD

**Issue by shileims** [haotian-liu/LLaVA#330]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Hi author,
    Thanks for your great work.
    When I input the same prompt to the model multiple times, different runs get different results? I would like to get the reason. Thank you!

**Comment by haotian-liu** [comment]
Hi, this is because of the *sampling* mechanism of the text generation process. After calculating the probability distribution of the next token, the default behavior currently is to sample from this probability distribution, and the more higher the probability is, the more likely that the model will output that token.

You can choose to set the deterministic sampling by setting `do_sample=False` in `model.generate`. 

This is an article that you can refer to for a better understanding of the generation process: https://huggingface.co/blog/how-to-generate.

**Comment by shileims** [comment]
hi @haotian-liu ,
    Really appreciate your reply. Will check the article. Thank you so much!
