### ISSUE TITLE
there is something wrong with the answer

### ISSUE THREAD

**Issue by FourthM** [haotian-liu/LLaVA#51]
![image](https://user-images.githubusercontent.com/117635816/233943750-4672927d-9846-4243-8078-1885594bd2fb.png)

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.

Could you try confirming the weights conversion process following the instruction [here](https://github.com/haotian-liu/LLaVA#llava-weights)?  The common issues are:
(1) you need to convert the weights from delta, due to LLaMA license issue;
(2) the base checkpoint should be llama, instead of vicuna.

Please let me know if you have further concerns, thanks!

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
