### ISSUE TITLE
[Question] If I want to continue to fine-tune the llava1.5 checkpoint, lora way, how should I change the script

### ISSUE THREAD

**Issue by hangzeli08** [haotian-liu/LLaVA#525]
### Question

I 
<img width="521" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/104003969/72c75374-2bf9-45c9-850b-2dd550fe52e8">
It report bug:
<img width="1220" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/104003969/0f0e16c8-4982-419f-84e7-32f414af4650">

**Comment by tingxueronghua** [comment]
@haotian-liu hi, do you have any advice about this topic? I am not familiar with PEFT library. I just change the model's path and face the same issue.
Because the time consumed by Llava-1.5 during fine-tuning stage is much longer than original llava, I think it might be a more efficient way to train an extra lora layer based on your fine-tuned llava-1.5 model. Hope to see your suggestion.

**Comment by tingxueronghua** [comment]
> ### Question
> I <img alt="image" width="521" src="https://user-images.githubusercontent.com/104003969/274173300-72c75374-2bf9-45c9-850b-2dd550fe52e8.png"> It report bug: <img alt="image" width="1220" src="https://user-images.githubusercontent.com/104003969/274173477-0f0e16c8-4982-419f-84e7-32f414af4650.png">

Hello? I guess I found the problem. This is mainly due to the confusion in the naming of the model layer, and the ambiguity of the parameters specifying the model layer in the LoraConfig input parameters.

The problem:

I guess you use the whole llava-1.5 model weights as the initialization. There would be minor difference between initializing with Vicuna. That is there will be a "mm_projector" if using llava-1.5, which contains Linear Layer. However, the function "find_all_linear_names" in llava/train/train.py, which is used to find which layers should be applied with Lora, will only memorize the last part of the name splited by ".". For example, if the model's name is "mm_projector.0" and is a Linear function which could be applied with Lora, then that function will only memorize the name "0". Unfortunately, the LlamaDecoderLayer is also named from "0" to "39" (for 13b case). 

The solution:
simply add 
```
if 'mm_projector' in names:
    continue
```
before 
```
lora_module_names.add(names[0] if len(names) == 1 else names[-1])
```


Then the problem is solved. Also you can specify the model name list manually.

**Comment by tingxueronghua** [comment]
There is one more thing you need to pay attention to. You need to manually set the "requires_grad" of mm_proj to be true. 

Because originally, llava add the mm_proj after adding lora layers. The operation of get_peft_model will set the rest parameters' requires_grad as False. If you load the projection layers first, then it will also be set as not-trainable parameters.

So, first, you need to ignore the parameter "pretrain_mm_mlp_adapter", then, you need to manually set the requires_grad of mm_proj after peft.

**Comment by wanghao-cst** [comment]
> There is one more thing you need to pay attention to. You need to manually set the "requires_grad" of mm_proj to be true.
> 
> Because originally, llava add the mm_proj after adding lora layers. The operation of get_peft_model will set the rest parameters' requires_grad as False. If you load the projection layers first, then it will also be set as not-trainable parameters.
> 
> So, first, you need to ignore the parameter "pretrain_mm_mlp_adapter", then, you need to manually set the requires_grad of mm_proj after peft.

Really good reply. Solved my problem.

**Comment by tingxueronghua** [comment]
> > There is one more thing you need to pay attention to. You need to manually set the "requires_grad" of mm_proj to be true.
> > Because originally, llava add the mm_proj after adding lora layers. The operation of get_peft_model will set the rest parameters' requires_grad as False. If you load the projection layers first, then it will also be set as not-trainable parameters.
> > So, first, you need to ignore the parameter "pretrain_mm_mlp_adapter", then, you need to manually set the requires_grad of mm_proj after peft.
> 
> Really good reply. Solved my problem.

In fact there is one more thing to do if want to use lora to further finetune the already finetuned model. 
Pay attention to the initialize_vision_modules in llava/model/llava_arch.py. There is a function named build_vision_projector. It won't check the existence of projection layer and will directly initialize a new one, rather than using the finetuned projection layer. So you need to manually disable it when you already have a projector.

I think that's all you need to tune llava1.5 checkpoint with lora.

**Comment by haotian-liu** [comment]
Hi, we have released the LoRA ckpt, script, and a brief doc on the new schedule.

https://github.com/haotian-liu/LLaVA/releases/tag/v1.1.3

**Comment by tingxueronghua** [comment]
Thanks for your effort! I have no other questions. And I think this issue could be closed.

> Hi, we have released the LoRA ckpt, script, and a brief doc on the new schedule.
> 
> https://github.com/haotian-liu/LLaVA/releases/tag/v1.1.3
