### ISSUE TITLE
[Usage] 

### ISSUE THREAD

**Issue by Carol-lyh** [haotian-liu/LLaVA#578]
Excuse me, What is the difference of v1 and plain on input argument --version?
And why mm_use_im_start_end and mm_use_im_patch_token are False here in your latest llava-v1.5??

**Comment by haotian-liu** [comment]
These are changes made for v1 checkpoints back in June/July.

Tokenization. We remove the dependency of the additional tokens (<IM_START>, <IM_END>, <IM_PATCH>), so that during the pretraining stage, the tokenizer does not change at all and we only update the linear projector weights.
Prompt.
Pretraining. We simplified the pretraining prompts by removing additional instructions like Describe the image details, which we find to allow the zero-shot inference and can slightly improve the training speed.

https://github.com/haotian-liu/LLaVA/releases/tag/v1.0.1
