### ISSUE TITLE
Inability to Reproduce Effective Results with ScienceQA

### ISSUE THREAD

**Issue by bigfanforChatGPT** [haotian-liu/LLaVA#59]
Hi there, 
I followed the instructions in the README to evaluate LLava-13B-ScienceQA's performance on the ScienceQA dataset. However, I noticed that the answers predicted by LLava seem to be significantly worse than the reported results in the paper. I'm wondering where the issue might be coming from. I'm confident that I've completed all the mentioned steps such as parameter conversion and dataset processing, etc. 
This is a great piece of work, and if this issue can be resolved, it would make a huge contribution to the research community.

Here are some examples:
"prompt":  ”What is the capital of Massachusetts?\nContext: N/A\nOptions: (A) Cambridge (B) Plymouth (C) Boston (D) Dover\n<image>", "text": "HALSOLUTERs"

"prompt":  “Look at the models of molecules below. Select the elementary substance.\nContext: N/A\nOptions: (A) carbon tetrachloride (B) acetaldehyde (C) bromine\n<image>", "text": ""

"prompt":  "What can Greta and Allie trade to each get what they want?\nContext: Trade happens when people agree to exchange goods and services. People give up something to get something else. Sometimes people barter, or directly exchange one good or service for another.\nGreta and Allie open their lunch boxes in the school cafeteria. Both of them could be happier with their lunches. Greta wanted broccoli in her lunch and Allie was hoping for tomatoes. Look at the images of their lunches. Then answer the question below.\nOptions: (A) Greta can trade her tomatoes for Allie's sandwich. (B) Allie can trade her broccoli for Greta's oranges. (C) Allie can trade her almonds for Greta's tomatoes. (D) Greta can trade her tomatoes for Allie's broccoli.\n<image>", "text": "H1.\nSOLUTION: Greta and Allie can trade tomatoes for broccoli to get what they want.“

"prompt":  "Is the following trait inherited or acquired?\nSasha is good at knitting hats.\nContext: Hint: People who can knit had to learn how to do it.\nOptions: (A) acquired (B) inherited", "text": "Assistant: LECTURE: Organisms, including people, have both inherited and acquired traits. Inherited and acquired traits are gained in different ways.\nInherited traits are passed down through families. Children gain these traits from their parents. Inherited traits do not need to be learned.\nAcquired traits are gained during a person's life. Some acquired traits, such as riding a bicycle, are gained by learning. Other acquired traits, such as scars, are caused by the environment. Children do not inherit their parents' acquired traits.\nSOLUTION: People are not born knowing how to knit. Instead, many people learn how to knit. Knitting well takes practice. So, knitting well is an acquired trait."

"prompt":  "What is the capital of Delaware?\nContext: N/A\nOptions: (A) Montpelier (B) Trenton (C) Dover (D) Georgetown\n<image>", "text": "SOLUTSOLUTSOLUTRs;'sOLs;'sOLs;'OLs;'OLs;OLs;'OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs ;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;OLs;"

**Comment by haotian-liu** [comment]
Hi @bigfanforChatGPT, thank you for your interest in our work.  We have tried to perform the inference on ScienceQA from scratch, meaning that we perform actions that a new user would need to do, including, weight conversion, and dataset download/conversion.

During this process, we did notice that an option was missing in the original instruction, which however, would not cause the garbled outputs above.  By adding that option back, we were able to reproduce the results.

The complete instruction is [here](https://github.com/haotian-liu/LLaVA#evaluation-1), including an updated script for conveniently running batch evaluation on multiple GPUs.  We hope this can further facilitate the research in this area.

Regarding the specific issue in the garbled outputs, it would be great if you could double check the [weight conversion process](https://github.com/haotian-liu/LLaVA#evaluation-1): (1) you would need to perform weight conversion for ScienceQA delta; (2) the base checkpoint should be llama instead of vicuna.

Please let me know if there are further issues.  Thank you!

**Comment by bigfanforChatGPT** [comment]
Hello @haotian-liu ,

Thank you very much for your prompt response. The new script and code are able to achieve the same performance as reported in the paper. Great job! However, I noticed that the difference between the new code and the previous one is that it runs the model twice to generate the answer. Is this similar to a two-stage method, where the first stage generates additional context and image captions, and the second stage predicts the answer? Are there any related ablation experiments using only a one-stage method? 

Good Job👍

**Comment by haotian-liu** [comment]
Yes, the current version is using CoT-like prompting, however, as mentioned in our paper, we do not notice a big difference in using CoT or not.  And you may notice that there is also a slight difference between ScienceQA model with our Chat model (SQA model is not using `<im_begin>` and `<im_end>` tokens).  These are due to the experiments are conducted in our early research stage.  We are working on a more comprehensive analysis of our models and more ablations.  Please stay tuned for our revised paper, and thank you again for your interest in our work.

**Comment by bigfanforChatGPT** [comment]
Sorry to bother you, but I'm still facing some difficulties when fine-tuning ScienceQA. When I followed your code for fine-tuning ScienceQA, the configs for the tokenizer and the model were not the same as the ones released.  Also, I'm not sure if the base model vicuna-13b was applied delta according to the code in the fastchat-v0. I'm currently using the model fastchat-v0 released and the code provided by you, but I'm encountering an error during fine-tuning:
'Using pad_token, but it is not set yet.'

**Comment by haotian-liu** [comment]
Hi @bigfanforChatGPT 

Do you see `error` or just `warning`.  This warning about `pad_token` is expected, and is set after the tokenizer is loaded.  If it is an error, can you please provide the full log?  Thanks.
