### ISSUE TITLE
[Question] Can you make the training log public?

### ISSUE THREAD

**Issue by July-zh** [haotian-liu/LLaVA#613]
### Question

Can you make the training log public?

**Comment by haotian-liu** [comment]
Thank you for your interest in our research! In our commitment to making our research fully transparent, we're pleased to release the wandb logs [here](https://api.wandb.ai/links/lht/6orh56wc).

We also put them in [MODEL ZOO](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#llava-v15) so that people can find them more easily.

**Comment by July-zh** [comment]
> Thank you for your interest in our research! In our commitment to making our research fully transparent, we're pleased to release the wandb logs [here](https://api.wandb.ai/links/lht/6orh56wc).
> 
> We also put them in [MODEL ZOO](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#llava-v15) so that people can find them more easily.

Thank you for doing such a great job!

**Comment by yuyq96** [comment]
@haotian-liu This url only contains the logs of the 13B model. Can you please provide the logs of the 7B model?
