### ISSUE TITLE
[Usage] Error when evaluate GQA

### ISSUE THREAD

**Issue by Carol-lyh** [haotian-liu/LLaVA#625]
### Describe the issue

I've commented scenes graphs since it does not exist. However, there is an error that:

Exception: Can't find testdev_balanced_all_questions.json

I checked the questions dir, and only find these two:
testdev_all_questions.json, testdev_balanced_questions.json

Is there anything wrong with the gqa eval.py? Should I change it to testdev_balanced_questions.json?

**Comment by miznchimaki** [comment]
just comment that line out, i.e. `choices = loadFile(args.choices.format(tier = args.tier))`
After commentint it out, maybe you will get another error and it is in the function named `updateConsistency`
then I commented out the function call of `updateConsistency`, finally it worked.

**Comment by Carol-lyh** [comment]
> just comment that line out, i.e. `choices = loadFile(args.choices.format(tier = args.tier))` After commenting it out, maybe you will get another error and it is in the function named `updateConsistency` then I commented out the function call of `updateConsistency`, finally it worked.

Thank you!
Excuse me, how can you fix this problem?
**Exception: Can't find testdev_balanced_all_questions.json**

I've checked the questions dir, and only find these two:
**testdev_all_questions.json, testdev_balanced_questions.json**

**Comment by miznchimaki** [comment]
> > just comment that line out, i.e. `choices = loadFile(args.choices.format(tier = args.tier))` After commenting it out, maybe you will get another error and it is in the function named `updateConsistency` then I commented out the function call of `updateConsistency`, finally it worked.
> 
> Thank you! Excuse me, how can you fix this problem? **Exception: Can't find testdev_balanced_all_questions.json**
> 
> I've checked the questions dir, and only find these two: **testdev_all_questions.json, testdev_balanced_questions.json**

I made a soft link named `testdev_balanced_all_questions.json`, pointing to `testdev_balanced_questions.json`.

**Comment by Carol-lyh** [comment]
> just comment that line out, i.e. `choices = loadFile(args.choices.format(tier = args.tier))` After commenting it out, maybe you will get another error and it is in the function named `updateConsistency` then I commented out the function call of `updateConsistency`, finally it worked.

Also, has another question that, I think the `choices` param is required in evaluating performances. Since it's used in many places in `eval.py`, not just in the function call of `updateConsistency`.

**Comment by miznchimaki** [comment]
> > just comment that line out, i.e. `choices = loadFile(args.choices.format(tier = args.tier))` After commenting it out, maybe you will get another error and it is in the function named `updateConsistency` then I commented out the function call of `updateConsistency`, finally it worked.
> 
> Also, has another question that, I think the `choices` param is required in evaluating performances. Since it's used in many places in `eval.py`, not just in the function call of `updateConsistency`.

maybe you're right and there exists some problems with my practice, but when I evaluated the 13B LLaVA-v1.5 ckpt which I reproduced, I only cared about the `accuracy` metric of GQA benchmark. Below is my reproduction results on GQA (62.60% vs 63.3% in llava-v1.5 paper. It seems that it has no effects on `accuracy` metric, because I also try it on the author's ckpt on hugging face):
Binary: 79.68%
Open: 48.11%
Accuracy: 62.60%
Distribution: 1.56 (lower is better)

Accuracy / structural type:
  choose: 83.97% (1129 questions)
  compare: 64.18% (589 questions)
  logical: 77.81% (1803 questions)
  query: 48.11% (6805 questions)
  verify: 83.08% (2252 questions)

Accuracy / semantic type:
  attr: 69.17% (5186 questions)
  cat: 52.65% (1149 questions)
  global: 61.78% (157 questions)
  obj: 88.43% (778 questions)
  rel: 54.58% (5308 questions)

Accuracy / steps number:
  1: 79.75% (237 questions)
  2: 57.47% (6395 questions)
  3: 64.81% (4266 questions)
  4: 69.48% (793 questions)
  5: 77.25% (822 questions)
  6: 87.80% (41 questions)
  7: 95.00% (20 questions)
  8: 100.00% (3 questions)
  9: 100.00% (1 questions)

Accuracy / words number:
  3: 39.74% (151 questions)
  4: 56.51% (630 questions)
  5: 50.85% (1290 questions)
  6: 59.16% (2074 questions)
  7: 63.28% (1642 questions)
  8: 62.95% (1185 questions)
  9: 67.37% (1281 questions)
  10: 68.45% (1249 questions)
  11: 63.78% (994 questions)
  12: 67.40% (638 questions)
  13: 64.50% (462 questions)
  14: 70.72% (345 questions)
  15: 70.04% (237 questions)
  16: 78.63% (117 questions)
  17: 70.21% (94 questions)
  18: 77.63% (76 questions)
  19: 79.07% (43 questions)
  20: 71.88% (32 questions)
  21: 68.42% (19 questions)
  22: 75.00% (12 questions)
  23: 25.00% (4 questions)
  24: 100.00% (2 questions)
  25: 100.00% (1 questions)
  The content above is all my own practice and opinions, I can't make sure that they're all correct.

**Comment by Carol-lyh** [comment]
Thank you so much for discussing the results with me! Through I still have problems in evaluating this benchmark, and I haven't figure this out. I've learned a lot from your experience! Lots of thanks !!!

**Comment by Carol-lyh** [comment]
And after comment out all the usage in `choices`, actually I GET the accuracy metric. You're right. Because  I only cared about the `accuracy` metric of GQA benchmark. 
Many many thanks

**Comment by LuFan31** [comment]
> Exception

Hi, I also encountered the same error, but I don't have testdev_all_questions.json and testdev_balanced_questions.json. May I ask where to obtain these two files and whether they should be placed in the path specified by the GQADIR parameter in gqa.sh?
