### ISSUE TITLE
a plan for using vicuna delta v1.1

### ISSUE THREAD

**Issue by jun297** [haotian-liu/LLaVA#66]
Is there a plan for using vicuna delta v1.1?
Or is it possible to directly train with v1.1 on my own?

**Comment by haotian-liu** [comment]
Hi @jun297, thank you for your interest in our work.

We are working on the updated model weights based on Vicuna delta v1.1, and it is planned for releasing next week.  However, since there are changes in tokenizer and special tokens between vicuna-v0 and v1.1, so the current code base does not natively support changing the backbone and train (similarly, FastChat-v0 is not compatible with v1.1 as well).

We will update the code base once we finish the verification, thanks.
