### ISSUE TITLE
[Usage] IndexErrors while finetuning on my own dataset, cur_image_idx out of bounds

### ISSUE THREAD

**Issue by yjt-okkk** [haotian-liu/LLaVA#732]
### Describe the issue

Issue:
IndexErrors while finetuning on my own dataset

Command:
```
deepspeed /home/jovyan/work/llava/LLaVA/llava/train.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed /home/jovyan/work/llava/LLaVA/scripts/zero3.json \
    --model_name_or_path /home/jovyan/work/model/llava-med/finetune_e2e_on_instruct_caption_in_text_cleaned-60k-3epoch \
    --version v1 \
    --data_path /home/jovyan/work/llava_data/llava_data_train.json \
    --image_folder /home/jovyan/work/ln_data \
    --vision_tower /home/jovyan/work/model/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-med-7b-task-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 0 \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
 File "/home/jovyan/work/llava/LLaVA/llava/model/llava_arch.py", line 154, in prepare_inputs_labels_for_multimodal
    cur_image_features = image_features[cur_image_idx]
IndexError: index 2 is out of bounds for dimension 0 with size 2

```

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/100284767/165b0607-854b-46ab-a8c7-cf60a3eddb42)

**Comment by kzleong** [comment]
@White1973 @yjt-okkk Did you manage to solve it? I'm facing the same issue too

**Comment by accordtsai** [comment]
I had this issue also, and solved it by fixing my prompt.

During training, the prompt is formatted `<image>\nHow many people are in this picture?`
However, during inference, the `<image>` tag is not needed, and should be formatted like `How many people are in this picture?`

Fixing the prompt solvesd the IndexError issue for me.

**Comment by ayensujeremiah** [comment]
Did any one here resolve this issue?

my data is a json that has both image-text samples and text-only samples…(samples with only conversation) mixed

initially I thought it was the mixture causing the error, so I regenerated one with all samples being image-text and still had this same error

Quite annoying because when I try some dataset it works, but my main dataset I want to use doesn’t.

**Comment by ayensujeremiah** [comment]
And yeah

i have the image token <image> in all image samples, so I am not sure why it is not working

**Comment by SWHL** [comment]
I met the same problem. 
I successfully reproduce it by repeating the data which has `<image>` strings more than one. 
The data is as following:
```json
[
    {
        "id": "xxxx",
        "image": "xxxx",
        "conversations": [
            {
                "from": "human",
                "value": "<image>\nRead the following text: <doc> Группа GO \n Элемент   <coverpage> \n Описание - Содержит ссылку на графическое изображение обложки книги. \n Нет атрибутов. Должен содержать элементы изображений: \n <image> 1..n (один или несколько, один обязателен). \n Может содержаться в следующих элементах: \n <title-info> 0..1 (один, опционально); \n <src-title-info; 0..1 (один, опционально). \n Пример использования \n <coverpage><image l:href=\"#cover.jpg\"/></coverpage> \n Элемент    <image> \n Описание - Картинка, иллюстрация в тексте. \n Определены два типа картинок: обычные (imageType) и внутри текста (inlineImageType). \n Атрибуты \n xlink:type (опциональный) \n xlink:href - ссылка на собственно графические данные, обычно содержащиеся в элементе \n <binary>; \n alt (опциональный); \n title (опциональный, для inline недопустимый) - подпись к картинке; \n id (опциональный, для inline недопустимый) - для ссылок на картинку. \n Нет подчиненных элементов, обычно нет закрывающего тэга (пустой элемент). \n Может содержаться в следующих элементах: \n Для обычных:"
            },
            {
                "from": "gpt",
                "value": "<body>; \n <section>. \n Для inline: \n <coverpage>; \n <p>; \n <v>; \n <subtitle>; \n <th> (с версии 2.1); \n <td> (с версии 2.1); \n <text-author> (с версии 2.1). </doc>"
            }
        ]
    }
]
```

Maybe that's the reason for the error.

**Comment by dcompgriff** [comment]
I think this is a bug when there are no images in a batch. I think it's this line https://github.com/haotian-liu/LLaVA/blob/main/llava/model/llava_arch.py#L240. For the life of me I cannot figure our why 'cur_image_idx += 1' when there are no images in the list of tokens since cur_image_idx is the location of the next image feature to be processed. 

Their code gets cur_image_features as 'cur_image_features = image_features[cur_image_idx]', but then a few lines later do 'cur_input_embeds = torch.cat([cur_input_embeds_1, cur_image_features[0:0]], dim=0)'. But cur_image_features[0:0] results in just an empty tensor. So, why?

**Comment by KejiaZhang-Robust** [comment]
It seems that the current iteration process in mPLUG-OWL2 results in issues with reusing the conv object. Each time a new message is appended to conv, it accumulates all previous messages, leading to unintended results during inference with multiple text pairs.

To address this, it’s important to reset conv at the start of each iteration rather than continually appending messages. This way, each inference run begins with a fresh conversation state, avoiding the problem of carrying over previous context.

Here’s a suggested approach to resolve this issue:
	1.	Reinitialize conv at each iteration: Instead of appending new messages to conv, reset conv at the start of each iteration by reassigning it from conv_templates["mplug_owl2"].copy().
	2.	Set the new input prompt each time: After resetting conv, set inp = DEFAULT_IMAGE_TOKEN + args.prompt, then add messages using conv.append_message() as before.

Here’s an example for clarity:
```
for text_pair in text_pairs:
    # Reinitialize conv for a clean conversation state
    conv = conv_templates["mplug_owl2"].copy()
    
    # Set up the prompt and conversation messages
    inp = DEFAULT_IMAGE_TOKEN + text_pair["prompt"]
    conv.append_message(conv.roles[0], inp)
    conv.append_message(conv.roles[1], None)
    prompt = conv.get_prompt()
    
    # Proceed with inference as before
    input_ids = tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors='pt').to(model.device)
    
    # [Additional inference code...]
```
This method ensures that conv doesn’t accumulate previous messages, maintaining the intended behavior for each text pair in your iterations.

Hope this helps resolve the issue!
