### ISSUE TITLE
[Question] Do we need to add "--tune_mm_mlp_adapter True" in finetuning?

### ISSUE THREAD

**Issue by Rickylht** [haotian-liu/LLaVA#917]
### Question

Do we need to add "--tune_mm_mlp_adapter True" in finetuning?
Since the official scripts didn't add this parameter.
![image](https://github.com/haotian-liu/LLaVA/assets/38951435/b27ae150-c5f9-438c-8393-2f3d384e54a8)

And the official paper said we need to tune the adapter in finetuning stage.
![image](https://github.com/haotian-liu/LLaVA/assets/38951435/6a8af063-1ecf-4140-b41f-b41ba7ebe7d7)

**Comment by unmo** [comment]
I had the same question. May I ask you to tell me about this one?

**Comment by tetsu-kikuchi** [comment]
`tune_mm_mlp_adapter` seems to be a flag to tune **_only_** mm_mlp_adapter (so tune_only_mm_mlp_adapter would be a more appropriate name).  

It should be set `True` at pretraining, while `False` at fine-tuning since we also want to tune parameters in a language model in the latter case. 

https://github.com/haotian-liu/LLaVA/blob/3e337ad269da3245643a2724a1d694b5839c37f9/llava/train/train.py#L927-L930
